name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: doocs/leetcode


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: site
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_REPO }}:latest .
      - name: Login to DockerHub
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ env.DOCKER_REPO }}:latest
